### ISSUE TITLE
Threshold ranges without inclusive of endpoints

### ISSUE THREAD

**Issue by ritmas** [aerospike/aerospike-nagios#12]
According to [Nagios' format](https://nagios-plugins.org/doc/guidelines.html#THRESHOLDFORMAT), threshold range `@10:20` should be resolved as:
```
≥ 10 and ≤ 20, (inside the range of {10 .. 20})
```
but it's [coded](https://github.com/aerospike/aerospike-nagios/blob/develop/aerospike_nagios.py#L664) (same goes to warning level also) as:
```
elif value > crit["start"] and value < crit["end"]:
```
rather than:
```
elif value >= crit["start"] and value <= crit["end"]:
```
Is there a reason why range is not inclusive of endpoints?

**Comment by hbpatre** [comment]
Thanks for pointing this out. It was mistake, we will fix it.

**Comment by hbpatre** [comment]
We have fixed this issue and merged changes to develop branch. Thanks.
