### ISSUE TITLE
YAMLLoadWarning on PyYAML 5.1

### ISSUE THREAD

**Issue by ritmas** [aerospike/aerospike-nagios#14]
I'm getting this error:
```
check_aerospike.py:623: YAMLLoadWarning: calling yaml.load() without Loader=... 
is deprecated, as the default Loader is unsafe.
Please read https://msg.pyyaml.org/load for full details.
  schema = yaml.load(schema_file)
```
It seems it's due to PyYAML version 5.1 and higher: https://stackoverflow.com/questions/55677397/why-does-pyyaml-5-1-raise-yamlloadwarning-when-the-default-loader-has-been-made

**Comment by spkesan** [comment]
@ritmas 
Thanks for reporting. It's a WARNING to safeguard against untrusted input to `yaml.load()`
The plugin just uses `yaml.load()` to convert `aerospike_schema.yaml` into a python object.
https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation
We'll fix this.
