### ISSUE TITLE
Unexpected indentation

### ISSUE THREAD

**Issue by broferek** [aerospike/aerospike-nagios#2]
I had this error when running the script the first time. I fixed it by respecting the indentation of the "if" clause.

 python ./aerospike.py 
  File "./aerospike.py", line 254
    append_perf=True
    ^
IndentationError: unexpected indent

**Comment by whyrg** [comment]
Thank you for the feedback! This issue has now been fixed.

**Comment by sandeeppalla** [comment]
Hi ,

I am facing the same problem. Can you let me know how did you fix this problem.

**Comment by whyrg** [comment]
There has been several updates to our Nagios plugin since this fix. It is recommended to update to our latest.

The fix for this specific issue was the following commit (replacing the tabs with 4 spaces):
https://github.com/aerospike/aerospike-nagios/commit/fcb5a4dd99b59754dcf7994706d14ad051d32e75
