### ISSUE TITLE
Import error -Aerospike Nagios integration

### ISSUE THREAD

**Issue by sandeeppalla** [aerospike/aerospike-nagios#4]
HI,

I am trying to monitor aerospike using Nagios. Below is the command and error from the output. Can you please help on this.

[root@]# ./aerospike_nagios.py -w 14000 -c 14500 -h 127.0.0.1 -p 3000 -s used-bytes-disk
Traceback (most recent call last):
  File "./aerospike_nagios.py", line 32, in <module>
    import aerospike
ImportError: No module named aerospike

**Comment by whyrg** [comment]
You would need to install the Aerospike python client on the system the plugin is running on.

If your system has Python PIP installed, you can install our client easily via:
`pip install aerospike`

**Comment by sandeeppalla** [comment]
Hi,

Thank you for info. Aerospike is already installed on the server. Below is status
[root@STP]# aql
Aerospike Query
Copyright 2013-2015 Aerospike. All rights reserved.

aql> 

Please let me know if any thing need to be installed

**Comment by whyrg** [comment]
You have the _server_ installed, but the plugin requires a _client_ to query the server as well.

The aerospike nagios plugin is built utilizing our _python client_. This client needs to be installed before the script can be used.

To install our python client, run `sudo pip install aerospike`.
