### ISSUE TITLE
Crashes of ingraph-collector

### ISSUE THREAD

**Issue by pausen** [aerospike/aerospike-nagios#5]
Hi,

we had a problem with you script and icinga/ingraph from netways. 

The problem is when you use the range parameter "@" in you script  ingraph-collector will crash with the error invalid literal for float(): @20 

We fixed it with stripping away the '@' at the end of your script when it generates the string for the performance data. 

we changed 

```
    if append_perf:
        print '%s|%s=%s;%s;%s' % (stat_line,arg_stat,perf_stat,arg_warning,arg_critical) 
    else:
```

to 

```
    if append_perf:
        warn_newstr = arg_warning.replace("@", "")
        crit_newstr = arg_critical.replace("@", "")
        print '%s|%s=%s;%s;%s' % (stat_line,arg_stat,perf_stat,warn_newstr,crit_newstr)
    else:
```

Maybe there is a better solution but for us it worked 

Regards 

Pausen

**Comment by whyrg** [comment]
Hi Pausen,

According to [Nagios plugin guidelines](https://nagios-plugins.org/doc/guidelines.html#AEN200),  and [Icinga docs](https://docs.icinga.com/latest/en/perfdata.html) the "warn and crit are in the range format [as Threshold and Ranges]" for performance data.

I would open an issue with Netways over support for thresholds and ranges in perfdata for ingraph-collector. Our aerospike-nagios plugin is working as intended.

Regards
Richard
