### ISSUE TITLE
Cannot retrieve expired_objects from namespace

### ISSUE THREAD

**Issue by ra-dft** [aerospike/aerospike-nagios#8]
Hello, 

It would seem that "-s expire_objects" only works when there is no "-n <ns>" provided .  Otherwise receive the "..is not a known statistic" error.  Although "expired_objects" exists under the namespace context in the aerospike_schema.yaml.

**Comment by whyrg** [comment]
Which server version are you monitoring? I'm unable to reproduce locally:

```
$ asd --version
Aerospike Enterprise Edition build 3.12.1
$ ./aerospike_nagios.py  -n test -s expired_objects -w 0 -c 0
Aerospike Stats - expired_objects=0|expired_objects=0.0c;0;0
$ ./aerospike_nagios.py  -s expired_objects -w 0 -c 0
expired_objects is not a known statistic.
```

**Comment by ra-dft** [comment]
Aerospike Enterprise Edition build 3.8.2.4

**Comment by whyrg** [comment]
Ah, before Aerospike Server 3.9 it was on the older set of metric names.

General stats contain `stat_expired_objects`, which sums over all namespaces. This was determined not very useful and hence removed in 3.9+.

Namespace metrics contain `expired-objects`. Note the dash, not underscore, for pre-3.9 server versions.

**Comment by ra-dft** [comment]
ahh ok, this resolves the expired-objects issue.  Now, just one more question(read in Columbo's voice).  We've got our eye on adding device_free_pct and hwm_breached.  I get the same "X is not a know statistic".  I guess this is a similar issue between 3.9+ and 3.8?

**Comment by whyrg** [comment]
You can see on our reference metric page:
http://www.aerospike.com/docs/reference/metrics

If you searched for "device_free", you'll see that `device_free_pct` was introduced in 3.9, and the stat was formerly `free-pct-disk`. Similarly with "hwm_breached", it was `hwm-breached` before 3.9 (again dashes vs underscores). You can find an explanation of our metrics changes at: http://www.aerospike.com/docs/operations/upgrade/stats_to_3_9

You can also find some hints as to where metrics moved to/from in the schema file's comments, especially for metrics that had significant renaming.

**Comment by ra-dft** [comment]
Thank you whyrg much appreciated.
